In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df =pd.read_csv("01 covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
x = df.iloc[:,0:5]
y = df.drop(x, axis = 'columns')
print(x.head())
print()
print()
print()
print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
print(x_train.head())
print()
print()
print(y_test.head())

    age  gender  fever   cough    city
55   81  Female  101.0    Mild  Mumbai
91   38    Male    NaN    Mild   Delhi
7    20  Female    NaN  Strong  Mumbai
49   44    Male  104.0    Mild  Mumbai
29   34  Female    NaN  Strong  Mumbai


   has_covid
93       Yes
84        No
38       Yes
0         No
86       Yes

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
si = SimpleImputer()

In [ ]:
y_train.has_covid = le.fit_transform(y_train.has_covid)
y_test.has_covid = le.transform(y_test['has_covid'])

In [ ]:
x_train.fever = si.fit_transform(x_train[['fever']])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder()
x_train['cough'] = oe.fit_transform(x_train[['cough']])
x_test['cough'] = oe.transform(x_test[['cough']])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first',sparse_output= False)

In [ ]:
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])
x_test_gender_city = ohe.transform(x_test[['gender', 'city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [ ]:
x_train

    age  gender       fever  cough     city
55   81     0.0  101.000000    0.0   Mumbai
91   38     1.0  100.930556    0.0    Delhi
7    20     0.0  100.930556    1.0   Mumbai
49   44     1.0  104.000000    0.0   Mumbai
29   34     0.0  100.930556    1.0   Mumbai
..  ...     ...         ...    ...      ...
15   70     1.0  103.000000    1.0  Kolkata
9    64     0.0  101.000000    0.0    Delhi
69   73     0.0  103.000000    0.0    Delhi
75    5     1.0  102.000000    0.0  Kolkata
90   59     0.0   99.000000    1.0    Delhi

[80 rows x 5 columns]

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = [('trans1', SimpleImputer(), ['fever']),
               ('trans2', OrdinalEncoder(categories = [['Mild','Strong']]),['cough']),
               ('trans3', OneHotEncoder(sparse_output = False, drop = 'first'), ['gender', 'city'])
               ]

In [ ]:
ct = ColumnTransformer(transformers = transformer, remainder = 'passthrough').set_output(transform = 'pandas')

In [ ]:
x_train_trans = ct.fit_transform(x_train)

In [ ]:
x_test_trans = ct.transform(x_test)

In [ ]:
print(x_test_trans.sample(5))
print()
print()
print(x_train_trans.shape)

    trans1__fever  trans2__cough  trans3__gender_Male  trans3__city_Delhi  \
22           98.0            1.0                  0.0                 0.0
70          101.0            1.0                  0.0                 1.0
73           98.0            1.0                  1.0                 0.0
10          101.0            0.0                  0.0                 1.0
39          103.0            0.0                  0.0                 0.0

    trans3__city_Kolkata  trans3__city_Mumbai  remainder__age
22                   1.0                  0.0              71
70                   0.0                  0.0              68
73                   1.0                  0.0              34
10                   0.0                  0.0              75
39                   1.0                  0.0              50


(80, 7)