In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"00 Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
x = df[['Age','EstimatedSalary']]
y = df['Purchased']
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test, y_train, y_test = train_test_split(
x,
y,
test_size=0.2,
random_state=1)

In [12]:
x_train

     Age  EstimatedSalary
93    29            28000
23    45            22000
299   46           117000
13    32            18000
90    22            81000
..   ...              ...
255   52            90000
72    20            23000
396   51            23000
235   46            79000
37    30            49000

[320 rows x 2 columns]

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
ss = StandardScaler().set_output(transform='pandas')

In [20]:
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

In [21]:
x_train_scaled

          Age  EstimatedSalary
93  -0.803301        -1.191218
23   0.756980        -1.368598
299  0.854498         1.439920
13  -0.510748        -1.486851
90  -1.485924         0.375639
..        ...              ...
255  1.439603         0.641709
72  -1.680959        -1.339035
396  1.342085        -1.339035
235  0.854498         0.316513
37  -0.705783        -0.570388

[320 rows x 2 columns]

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
lr = LogisticRegression()
lr_scaled = LogisticRegression()

In [36]:
lr.fit(x_train, y_train)

LogisticRegression()

In [38]:
lr_scaled.fit(x_train_scaled, y_train)

LogisticRegression()

In [39]:
y_pred_unscaled = lr.predict(x_test)
y_pread_scaled = lr_scaled.predict(x_test_scaled)

In [69]:
from sklearn.metrics import accuracy_score

In [68]:
accuracy_unscaled = accuracy_score(y_pred_unscaled, y_test)
accuracy_scaled = accuracy_score(y_pread_scaled, y_test)
print(f"Accuracy on unscaled dataframe = {accuracy_unscaled}.\nAccuracy on scaled dataframe = {accuracy_scaled}.")

Accuracy on unscaled dataframe = 0.8375.
Accuracy on scaled dataframe = 0.8375.